#!/usr/bin/env bash
# Remove /sites-enabled/default file in nginx
cd /etc/nginx/sites-enabled/ || exit
rm default


# Create a symbolic link to default file in sites-available
ln -s /etc/nginx/sites-available/default default

# Restart nginx
service nginx restart
