#!/usr/bin/env bash
# Displays numbers from 1 to 100 but if number is:
#	a multiple of 3 and 5, Display FizzBuzz
#	a multiple of 3, Display "Fizz"
#	a multiple of 5, Display "Buzz"

for num in {1..100}
do
if (( num % 3 == 0 && num % 5 == 0 ))
then
echo "FizzBuzz"
elif (( num % 3  == 0 ))
then
echo "Fizz"
elif (( num % 5 == 0 ))
then
echo "Buzz"
else
echo "$num"
fi
done
