#!/usr/bin/env bash
# Displays Hi in 9th iteration of while loop displaying 'Best School' 10 times to the stdout

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((index++))
done
