#!/usr/bin/env bash
# Lops form 1 to 10 and displays:
#	"bad luck" for the 4th loop iteration
#	"good luck" for the 8th lop iteration
#	"Best School" for the other iterations

iteration=0

while [ $iteration -lt 10 ]
do
	if [ $iteration -eq 3 ]
	then
		echo "bad luck"
	elif [ $iteration -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((iteration++))
done
