#!/usr/bin/env bash
# Disaplays:
#	Contents of the current directory In a list format:
#	Only part of the name after the 1st dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
